### ISSUE TITLE
Error when returning to ImagePicker from landscape camera

### ISSUE THREAD

**Issue by jeungjeung** [nguyenhoanglam/ImagePicker#10]
Hi,

I have a SONY Xperia Z5 which the camera is default in landscape mode.

After I took a picture from the camera app and return to the picker, the picker became landscape too, even I am holding my phone up right.

Then I  shake a bit my phone trying to make the picker back to portrait. The following error was found.

java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage()' on a null object reference
  at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(ImagePickerActivity.java:545)
  at java.lang.Thread.run(Thread.java:818)

**Comment by jeungjeung** [comment]
With version 1.1.2, the problem is gone, nice work! and  thank you
