### ISSUE TITLE
Library Glide 4.9.0 app crash 

### ISSUE THREAD

**Issue by KishanViramgama** [nguyenhoanglam/ImagePicker#104]
`No virtual method placeholder(I)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.vpapp.videostatus-jQHfCWNqyPG9DKcuWQh8Aw==/split_lib_dependencies_apk.apk)`

`at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImageLoader.<init>(ImageLoader.java:22)
        at com.nguyenhoanglam.imagepicker.ui.imagepicker.RecyclerViewManager.<init>(RecyclerViewManager.java:56)
        at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.setupComponents(ImagePickerActivity.java:135)
        at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.java:111)`

**Comment by mehdiyari** [comment]
this error happened for me too with glide any version(3.8 and up)

**Comment by KishanViramgama** [comment]
@mehdiyari  please  same version use glide app module and library module **3.9.0**

#105 check this pull request

**Comment by mehdiyari** [comment]
@KishanViramgama iam using 4.9.0 but app crash with this version of glide too

**Comment by KishanViramgama** [comment]
@mehdiyari same glide version **app module and library module** 4.9.0
