### ISSUE TITLE
Getting below error.

### ISSUE THREAD

**Issue by pinvisible** [nguyenhoanglam/ImagePicker#2]
java.lang.NoSuchFieldError: No static field menu_add of type I in class Lcom/nguyenhoanglam/imagepicker/R$id; or its superclasses (declaration of 'com.nguyenhoanglam.imagepicker.R$id' appears in /data/data/com.trinityholisticsolutions.poojamedimart/files/instant-run/dex/slice-slice_6-classes.dex)
                                                                                                at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.onCreateOptionsMenu(ImagePickerActivity.java:145)
                                                                                                at android.app.Activity.onCreatePanelMenu(Activity.java:2850)
                                                                                                at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:358)
                                                                                                at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:88)
                                                                                                at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:270)
                                                                                                at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:88)
                                                                                                at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
                                                                                                at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)

**Comment by AstonBraham** [comment]
Same here...


I have found a quick dirty trick you can use while the author fixes this..
1- Rename your menu_main.xml to somethink like menu_principal.xml
2 - Copy menu_main.xml from this library's res/menu forlder to you app's res/menu folder and it should be done

**Comment by nguyenhoanglam** [comment]
@AstonBraham Do you have any solution for this error without renaming the menu file?

**Comment by AstonBraham** [comment]
Sure,

You can dynamically add the menu items..
Thus, you won't need to replace/reame/override ressource files..
I can open a pull request if needed to fix it..
I also noticed that the ImagePickerActivity doesn't use the default app theme

2016-08-10 2:38 UTC, Nguyen Hoang Lam <notifications@github.com>:

**Comment by AstonBraham** [comment]
Sure,

You can dynamically add the menu items..
Thus, you won't need to replace/reame/override ressource files..
I can open a pull request if needed to fix it..
I also noticed that the ImagePickerActivity doesn't use the default app theme

2016-08-10 9:55 UTC, SAMAH Abraham <abrah.smh@gmail.com>:

**Comment by nguyenhoanglam** [comment]
@pinvisible I've fixed the error. Please check it out and close this issue!
