### ISSUE TITLE
Crash Crash with Camera

### ISSUE THREAD

**Issue by khemmachattk** [nguyenhoanglam/ImagePicker#25]
E/AndroidRuntime: FATAL EXCEPTION: Thread-1217
                                                                     Process: com.modize.digicard, PID: 29429
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage()' on a null object reference
                                                                         at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(ImagePickerActivity.java:545)
                                                                         at java.lang.Thread.run(Thread.java:818)

**Comment by mansoorriaaz** [comment]
I have the same issue here, any fix for this?

java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage()' on a null object reference
                                                                        at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(ImagePickerActivity.java:545)
                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by Rainer-Lang** [comment]
@khemmachattk @mansoorriaaz Please try newest version.
@nguyenhoanglam Long time no reaction. Maybe close?

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam I suggest to close this issue. Right now I have no problems with v1.2.1
