### ISSUE TITLE
Crash when using camera 

### ISSUE THREAD

**Issue by junaidwarsi1994** [nguyenhoanglam/ImagePicker#34]
i am using your lattest library compile 'com.github.nguyenhoanglam:ImagePicker:1.1.1'
when i use camera option it gives concurent modification exception can u please help me to tackle that
: Exception 
 Process: com.example.invision.driverapplication, PID: 21913
                                                                                        java.util.ConcurrentModificationException
                                                                                            at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                                            at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$5.handleMessage(ImagePickerActivity.java:602)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5456)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by nguyenhoanglam** [comment]
I've tested this bug and no crash occured. However I changed some code lines and released ver 1.1.2.
Please try the new version and let me know if the bug is gone.

**Comment by mkhan07** [comment]
I have also used the library version 1.1.1 and found similar crash in crash log of live app. Please find stacktrace for the same

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.getFolder(SourceFile:825)
       at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(SourceFile:791)
       at java.lang.Thread.run(Thread.java:818)
------------------------------------------------------------------------
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$5.handleMessage(SourceFile:602)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5635)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by nguyenhoanglam** [comment]
Please try latest version !

`compile 'com.github.nguyenhoanglam:ImagePicker:1.1.2'`

**Comment by deannrchsnl** [comment]
I have also used the library version 1.1.2 and found similar crash in crash log of live app like @mkhan07  . 
Fatal Exception: java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.getFolder(SourceFile:825)
at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(SourceFile:791)

**Comment by kapoet** [comment]
have the same problem. I think the app crash because we are using folder mode

**Comment by Rainer-Lang** [comment]
@junaidwarsi1994 @mkhan07 @kapoet Could you test this with the newest version please? Maybe this issue could be closed.

**Comment by baokk** [comment]
@nguyenhoanglam Camera on Android >= 7 still error. Could please help to check on last version?

**Comment by nguyenhoanglam** [comment]
@baokk please show me the error description!

**Comment by nguyenhoanglam** [comment]
Hi guys,
Version 1.4.0 is now available. Please check it out and close this issue if the error's gone away!
Thank you so much!
