### ISSUE TITLE
Camera crash issue

### ISSUE THREAD

**Issue by AzamatEm** [nguyenhoanglam/ImagePicker#37]
Hello! I am getting issue when I try to make photo by camera
here is error log

FATAL EXCEPTION: main
                                                                 Process: ru.knamauto.droid, PID: 1481
                                                                 java.lang.RuntimeException: Unable to resume activity {ru.knamauto.droid/com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2000, result=-1, data=null} to activity {ru.knamauto.droid/com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity}: java.lang.NullPointerException: uriString
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3232)
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3263)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2606)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:178)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
                                                                  Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2000, result=-1, data=null} to activity {ru.knamauto.droid/com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity}: java.lang.NullPointerException: uriString
                                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3839)
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3214)
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3263) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2606) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:178) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                     at android.os.Looper.loop(Looper.java:194) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5637) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
                                                                  Caused by: java.lang.NullPointerException: uriString
                                                                     at android.net.Uri$StringUri.<init>(Uri.java:470)
                                                                     at android.net.Uri$StringUri.<init>(Uri.java:460)
                                                                     at android.net.Uri.parse(Uri.java:432)
                                                                     at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.onActivityResult(ImagePickerActivity.java:520)
                                                                     at android.app.Activity.dispatchActivityResult(Activity.java:6294)
                                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3835)
                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3214) 
                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3263) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2606) 
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:178) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                     at android.os.Looper.loop(Looper.java:194) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5637) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by AzamatEm** [comment]
Btw Android 5.1, phone Fly fs405

**Comment by Rainer-Lang** [comment]
@AzamatEm Please try the newest version, maybe this issue could be closed?
