### ISSUE TITLE
Camera Error

### ISSUE THREAD

**Issue by tank777** [nguyenhoanglam/ImagePicker#40]
FATAL EXCEPTION: main
                  Process: galaxy.tech.mobileexchangeradmin, PID: 24976
                  java.lang.IllegalThreadStateException: Thread already started
                      at java.lang.Thread.checkNotStarted(Thread.java:849)
                      at java.lang.Thread.start(Thread.java:1059)
                      at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.getData(ImagePickerActivity.java:345)
                      at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.access$1400(ImagePickerActivity.java:58)
                      at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$6.onChange(ImagePickerActivity.java:624)
                      at android.database.ContentObserver.onChange(ContentObserver.java:130)
                      at android.database.ContentObserver.onChange(ContentObserver.java:145)
                      at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
                      at android.os.Handler.handleCallback(Handler.java:815)
                      at android.os.Handler.dispatchMessage(Handler.java:104)
                      at android.os.Looper.loop(Looper.java:194)
                      at android.app.ActivityThread.main(ActivityThread.java:5624)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by Rainer-Lang** [comment]
You you give a bit more information? Maybe a bit of code?

@nguyenhoanglam I don't know, maybe you could close this very old issue.

**Comment by nguyenhoanglam** [comment]
@tank777  Please use version 1.2.0 and let me know if the camera error is gone
@Rainer-Lang Maybe he uses the old version that has camera bug. Thanks!
