### ISSUE TITLE
App closed on launching Image Picker code

### ISSUE THREAD

**Issue by pinvisible** [nguyenhoanglam/ImagePicker#44]
#### My Code

ImagePicker.create(this)
                .folderMode(true) // folder mode (false by default)
                .folderTitle("Folder") // folder selection title
                .imageTitle("Tap to select") // image selection title
                .single() // single mode
                .showCamera(true) // show camera or not (true by default)
                .start(123456); // start image picker activity with request code

#### Getting this error..

Error 1)   Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.Toolbar

Error 2)    Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f010082 a=-1}
                                                                    at android.content.res.TypedArray.getDrawable(TypedArray.java:867)
                                                                    at android.view.View.<init>(View.java:3951)
                                                                    at android.view.ViewGroup.<init>(ViewGroup.java:573)
                                                                    at android.view.ViewGroup.<init>(ViewGroup.java:569)
                                                                    at android.support.v7.widget.Toolbar.<init>(Toolbar.java:235)
                                                                    at android.support.v7.widget.Toolbar.<init>(Toolbar.java:231)
                                                                    at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:941) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                    at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.onCreate(ImagePickerActivity.java:119) 
                                                                    at android.app.Activity.performCreate(Activity.java:6245) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5443)

**Comment by Rainer-Lang** [comment]
@pinvisible Could you check it with the newest version?
@nguyenhoanglam Close this issue?
