### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by anvar1101** [nguyenhoanglam/ImagePicker#48]
java.util.ConcurrentModificationException
                                                       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                       at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$5.handleMessage(ImagePickerActivity.java:602)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by anvar1101** [comment]
java.util.ConcurrentModificationException\n\tat java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)\n\tat com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.getFolder(ImagePickerActivity.java:825)\n\tat com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(ImagePickerActivity.java:791)\n\tat java.lang.Thread.run(Thread.java:818)\n

**Comment by Rainer-Lang** [comment]
@anvar1101 Could you please test the newest version? Maybe this issue could be closed.
