### ISSUE TITLE
Urgent : App Crashing due to - java.lang.NullPointerException: uriString

### ISSUE THREAD

**Issue by pinvisible** [nguyenhoanglam/ImagePicker#49]
Hello ,

Thanks for such a nice library. Really like this.

I want to select only single image. I clicked camera, captured photo, but i am getting null result so app is crashing.

Code: 

 ImagePicker.create(this)
                .folderMode(true) // set folder mode (false by default)
                .folderTitle("Folder") // folder selection title
                .imageTitle("Tap to select") // image selection title
                .single() // single mode
                .showCamera(true) // show camera or not (true by default)
                .imageDirectory("Camera")   // captured image directory name ("Camera" folder by default)
                .origin(null) // original selected images, used in multi mode
                .start(12345); // start image picker activity with request code

Error : 

Caused by: java.lang.NullPointerException: uriString
                                                                    at android.net.Uri$StringUri.<init>(Uri.java:475)
                                                                    at android.net.Uri$StringUri.<init>(Uri.java)
                                                                    at android.net.Uri.parse(Uri.java:437)
                                                                    at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.onActivityResult(ImagePickerActivity.java:520)
                                                                    at android.app.Activity.dispatchActivityResult(Activity.java:6442)

**Comment by nguyenhoanglam** [comment]
I've just released version 1.1.3. Please check it out and let me know the result!

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam I think this could be closed. There was long time no reaction.

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Close this issue?
