### ISSUE TITLE
ImagePickerActivity NullPointerException

### ISSUE THREAD

**Issue by iffanmajid** [nguyenhoanglam/ImagePicker#55]
Got this from fabric:

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.os.Handler.obtainMessage()' on a null object reference
       at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(ImagePickerActivity.java:755)
       at java.lang.Thread.run(Thread.java:818)

Here's my code:
```java
if (requestCode == RC_CHANGE_IMAGE && resultCode == RESULT_OK && data != null) {
            ArrayList<Image> images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
            Image image = images.size() == 0 ? null : images.get(0);
            if (image != null) {
                Bitmap bitmap = ImageUtils.getScaledBitmap(image.getPath(), 720);
                imgProfile.setImageBitmap(bitmap);
                pictureImage = saveFile(bitmap);
            }
        }
```

**Comment by prasad456** [comment]
I'm getting the same issue in your sample code

`06-19 19:14:16.089 26182-26737/com.nguyenhoanglam.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-2191
                                                                           Process: com.nguyenhoanglam.sample, PID: 26182
                                                                           java.util.ConcurrentModificationException
                                                                               at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                               at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.getFolder(ImagePickerActivity.java:816)
                                                                               at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(ImagePickerActivity.java:782)
                                                                               at java.lang.Thread.run(Thread.java:818)`

**Comment by Rainer-Lang** [comment]
@iffanmajid @prasad456 I just downloaded the newest version and the sample app is running without any issue. Could you please check it again and report? Thanks.
