### ISSUE TITLE
Crash on just  Start

### ISSUE THREAD

**Issue by chnouman** [nguyenhoanglam/ImagePicker#65]
```
E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dixeam.millionarequotes/com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #4: Error inflating class <unknown>
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                                    at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                                 Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #4: Error inflating class <unknown>
                                                                                 Caused by: android.view.InflateException: Binary XML file line #4: Error inflating class <unknown>
                                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                                    at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                                    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976)
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                    at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.onCreate(ImagePickerActivity.java:119)
                                                                                    at android.app.Activity.performCreate(Activity.java:6942)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                                    at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                                 Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f010100 a=-1}
                                                                                    at android.content.res.TypedArray.getDrawable(TypedArray.java:942)
                                                                                    at android.view.View.<init>(View.java:4516)
                                                                                    at android.view.ViewGroup.<init>(ViewGroup.java:579)
                                                                                    at android.view.ViewGroup.<init>(ViewGroup.java:575)
                                                                                    at android.support.v7.widget.Toolbar.<init>(Toolbar.java:235)
                                                                                    at android.support.v7.widget.Toolbar.<init>(Toolbar.java:231)
                                                                                    at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:652) 
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) 
                                                                                    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:525) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:378) 
                                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                    at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.onCreate(ImagePickerActivity.java:119) 
                                                                                    at android.app.Activity.performCreate(Activity.java:6942) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                                    at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
08-23 19:07:37.296 21709-21709/com.dixeam.millionarequotes E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.dixeam.millionarequotes, PID: 21709
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dixeam.millionarequotes/com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #4: Error inflating class <unknown>
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                                 at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                              Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #4: Error inflating class <unknown>
                                                                              Caused by: android.view.InflateException: Binary XML file line #4: Error inflating class <unknown>
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                 at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.onCreate(ImagePickerActivity.java:119)
                                                                                 at android.app.Activity.performCreate(Activity.java:6942)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                                 at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                              Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f010100 a=-1}
                                                                                 at android.content.res.TypedArray.getDrawable(TypedArray.java:942)
                                                                                 at android.view.View.<init>(View.java:4516)
                                                                                 at android.view.ViewGroup.<init>(ViewGroup.java:579)
                                                                                 at android.view.ViewGroup.<init>(ViewGroup.java:575)
                                                                                 at android.support.v7.widget.Toolbar.<init>(Toolbar.java:235)
                                                                                 at android.support.v7.widget.Toolbar.<init>(Toolbar.java:231)
                                                                                 at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:652) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794) 
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:525) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:427) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:378) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                 at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity.onCreate(ImagePickerActivity.java:119) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6942) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                                 at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
```

**Comment by nguyenhoanglam** [comment]
@chnouman Please update to the lastest version and let me know if the bug is gone!

**Comment by chnouman** [comment]
ok i'll try at some time and let you know budy

**Comment by Rainer-Lang** [comment]
@chnouman Is this issue fixed? Could the issue be closed?
