### ISSUE TITLE
NullPointerException crash in ImageLoaderRunnable

### ISSUE THREAD

**Issue by duz17** [nguyenhoanglam/ImagePicker#74]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
       at java.io.File.fixSlashes(File.java:183)
       at java.io.File.<init>(File.java:130)
       at com.nguyenhoanglam.imagepicker.activity.ImagePickerActivity$ImageLoaderRunnable.run(ImagePickerActivity.java:776)
       at java.lang.Thread.run(Thread.java:818)

**Comment by nguyenhoanglam** [comment]
Hi @duz17 ,
Version 1.4.0 is now available. Please check it out and close this issue if the error's gone away!
Thank you so much!

**Comment by duz17** [comment]
it's been almost 3 years, I no longer have access to that code to verify

**Comment by nguyenhoanglam** [comment]
Fixed in v1.4.0
