### ISSUE TITLE
Getting Error when pressing back button in Picture chooser activity [when no image is selected]

### ISSUE THREAD

**Issue by YasirAmeen** [nguyenhoanglam/ImagePicker#8]
`08-16 05:05:26.330 24320-24320/yasirameen.com.googlemapdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: yasirameen.com.googlemapdemo, PID: 24320
                                                                              java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1000, result=0, data=null} to activity {yasirameen.com.googlemapdemo/invision.app.facebookclassified.activities.TimeLineActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList android.content.Intent.getParcelableArrayListExtra(java.lang.String)' on a null object reference
                                                                                  at android.app.ActivityThread.deliverResults(ActivityThread.java:3539)
                                                                                  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582)
                                                                                  at android.app.ActivityThread.access$1300(ActivityThread.java:144)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList android.content.Intent.getParcelableArrayListExtra(java.lang.String)' on a null object reference
                                                                                  at invision.app.facebookclassified.activities.TimeLineActivity.onActivityResult(TimeLineActivity.java:376)
                                                                                  at android.app.Activity.dispatchActivityResult(Activity.java:6135)
                                                                                  at android.app.ActivityThread.deliverResults(ActivityThread.java:3535)
                                                                                  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582) 
                                                                                  at android.app.ActivityThread.access$1300(ActivityThread.java:144) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
08-16 05:05:28.431 24320-24320/yasirameen.com.googlemapdemo I/Process: Sending signal. PID: 24320 SIG: 9`

**Comment by nguyenhoanglam** [comment]
I've tested on my device and there's no error as you mentioned. Make sure that you handle onAcvitityResult properly:
```java
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (requestCode == REQUEST_CODE_PICKER && resultCode == RESULT_OK && data != null) {
        ArrayList<Image> images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
        // do your logic ....
    }
}
```

Note: REQUEST_CODE_PICKER is your unique request code when  starting ImagePickerActivity

**Comment by YasirAmeen** [comment]
This is the code I am using.

` @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        switch (requestCode) {

            case REQUEST_CODE_PICKER_1:

                images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
                try
                {
                    String holderOne = images.get(0).getPath();
                    imageString = imageString + holderOne+"@";
                    Glide.with(this).load(holderOne).fitCenter().into(_img_one);
                }
                catch(Exception e)
                {
                    Log.e("MyActivity", e.getMessage());
                }
                break;

            case  REQUEST_CODE_PICKER_2:

                images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
                try
                {
                    String holderTwo = images.get(0).getPath();
                    imageString = imageString + holderTwo+"@";

                    Glide.with(this).load(holderTwo).fitCenter().into(_img_two);
                }
                catch(Exception e)
                {
                    Log.e("MyActivity", e.getMessage());
                }

                break;

            case REQUEST_CODE_PICKER_3:

                images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
                try
                {
                    String holderThree = images.get(0).getPath();
                    imageString = imageString + holderThree+"@";
                    Glide.with(this).load(holderThree).fitCenter().into(_img_three);
                }
                catch(Exception e)
                {
                    Log.e("MyActivity", e.getMessage());
                }

                break;

            case REQUEST_CODE_PICKER_4:

                images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
                try
                {
                    String holderFour = images.get(0).getPath();
                    imageString = imageString + holderFour+"@";
                    Glide.with(this).load(holderFour).fitCenter().into(_img_four);
                }
                catch(Exception e)
                {
                    Log.e("MyActivity", e.getMessage());
                }

                break;

            case REQUEST_CODE_PICKER_5:

                images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
                try
                {
                    String holderFive = images.get(0).getPath();
                    imageString = imageString + holderFive+"@";

                    Glide.with(this).load(holderFive).fitCenter().into(_img_five);
                }
                catch(Exception e)
                {
                    Log.e("MyActivity", e.getMessage());
                }

                break;

            case REQUEST_CODE_PICKER_MULTI:

                images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);
                try
                {
                    StringBuffer stringBuffer = new StringBuffer();
                    for (int i = 0, l = images.size(); i < l; i++) {
                        stringBuffer.append(images.get(i).getPath() + "@");
                    }

                    imageString = imageString + stringBuffer.toString();
                }
                catch(Exception e)
                {
                    Log.e("MyActivity", e.getMessage());
                }
                break;
            
                default:                    
                break;`

**Comment by nguyenhoanglam** [comment]
Your code has a mistake!
Because when you press back button, the result code will be _RESULT_CANCELED_ and no data returned. So if you do:

`images = data.getParcelableArrayListExtra(ImagePickerActivity.INTENT_EXTRA_SELECTED_IMAGES);`

The`images` will be null and the error occurs. To avoid this, you need to check whether result code is _RESULT_OK_ :

```
if(resultCode == RESULT_OK){
      // your switch case here...
}
```

**Comment by YasirAmeen** [comment]
Dear nguyenhoanglam,

Now code is working without error.
Thank  you for the support once again :-) 


Thanks

**Comment by nguyenhoanglam** [comment]
You deserve it!
