### ISSUE TITLE
Glide 4.4.0 not working

### ISSUE THREAD

**Issue by kamleshnarola** [nguyenhoanglam/ImagePicker#82]

**Comment by nguyenhoanglam** [comment]
Please tell me more about your error!

**Comment by kantawalahusain** [comment]
java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.anywayapp-1/split_lib_dependencies_apk.apk)
                                                                 at com.nguyenhoanglam.imagepicker.ui.imagepicker.ImageLoader.loadImage(ImageLoader.java:32)
                                                                 at com.nguyenhoanglam.imagepicker.adapter.FolderPickerAdapter.onBindViewHolder(FolderPickerAdapter.java:43)
                                                                 at com.nguyenhoanglam.imagepicker.adapter.FolderPickerAdapter.onBindViewHolder(FolderPickerAdapter.java:22)
                                                                 at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                 at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)

**Comment by amitks2015** [comment]
Is this issue fixed? I also get the same error with glide version 4.6.1

**Comment by mindshifter** [comment]
same issue here 👍

**Comment by anuj4994** [comment]
Any fix?

**Comment by musacibik** [comment]
Same here

**Comment by banyanandroid** [comment]
same issue here too, what is fix

**Comment by pdapnz** [comment]
Same problem PR https://github.com/nguyenhoanglam/ImagePicker/pull/91 should fix this problem.

**Comment by nguyenhoanglam** [comment]
@kamleshnarola @kantawalahusain @mindshifter @musacibik Please check version 1.3.0 and let me know if the issue is solved!
