### ISSUE TITLE
Crash in android O : Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by devganiyahitesh1** [nguyenhoanglam/ImagePicker#87]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.medic/com.nguyenhoanglam.imagepicker.ui.camera.CameraActivty}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                               at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                               at android.os.Handler.dispatchMessage(Handler.java:105)
                                                               at android.os.Looper.loop(Looper.java:164)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                            Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                               at android.app.Activity.onCreate(Activity.java:986)
                                                               at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
                                                               at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:297)
                                                               at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
                                                               at com.nguyenhoanglam.imagepicker.ui.camera.CameraActivty.onCreate(CameraActivty.java:42)
                                                               at android.app.Activity.performCreate(Activity.java:6975)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
```

**Comment by attaullahpro** [comment]
Set Orientation of activity in Manifiest.xml
android:screenOrientation="unspecified"

**Comment by abroresonaliyev** [comment]
> Set Orientation of activity in Manifiest.xml
> android:screenOrientation="unspecified"

I use this library with gradle. where I must set ` android:screenOrientation="unspecified"
`

**Comment by attaullahpro** [comment]
> 
> 
> > Set Orientation of activity in Manifiest.xml
> > android:screenOrientation="unspecified"
> 
> I use this library with gradle. where I must set `android:screenOrientation="unspecified"`

in manifiest.xml or you may also set on activity using java code

**Comment by adamGT** [comment]
I run in to the same issues, Tried setting the screenOrientation to both "portrait" & "unspecified" still i get the same error. I even tried to set it on the java code.
