### ISSUE TITLE
Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by jerinamathews** [nguyenhoanglam/ImagePicker#92]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugManifest'.
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Manifest merger failed with multiple errors, see logs
	at com.android.builder.core.AndroidBuilder.mergeManifestsForApplication(AndroidBuilder.java:524)
	at com.android.build.gradle.tasks.MergeManifests.doFullTaskAction(MergeManifests.java:143)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)

**Comment by jerinamathews** [comment]
I solved it. 
The problem was, I had a file provider in my manifest, which caused the error.
so I removed it and the build again. Its working fine now.

**Comment by nguyenhoanglam** [comment]
Hope you be satisfy with the lib. By the way, please close this issue. Thanks!
